### Main page
GET https://localhost:8081
Content-Type: application/json

### Init
POST https://localhost:8081/init
Content-Type: application/json

{
  "id": 1,
  "name": "John Doe"
}

### Level choose
POST https://localhost:8081/level-choose
Content-Type: application/json

{
  "id": 1,
  "level": "easy"
}

### Gamoe move
POST https://localhost:8081/game-move
Content-Type: application/json

### Scores
GET https://localhost:8081/scores
Content-Type: application/json

###
