### Main page
GET https://localhost:8081
Accept: application/json

### Start session
POST https://localhost:8081/session-start
Accept: application/json

### Level choose
POST https://localhost:8081/level-choose
Accept: application/json

### Gamoe move
POST https://localhost:8081/game-move
Accept: application/json

### Scores
GET https://localhost:8081/scores
Accept: application/json

###
